### ISSUE TITLE
It seems to stop working

### ISSUE THREAD

**Issue by dongerlel** [HOAIAN2/Instagram-Downloader#10]
![image](https://github.com/HOAIAN2/Instagram-Downloader/assets/12804761/35be42d6-4ad7-4a80-be6e-ca8a2d93d396)

https://www.instagram.com/tyrone/p/C2fB7nZuQU2/?img_index=2

**Comment by dongerlel** [comment]
Nvm i was using old version because it's default on the mainpage

![image](https://github.com/HOAIAN2/Instagram-Downloader/assets/12804761/f7efcdc5-4b1b-4399-b9de-1214322c3dbc)

**Comment by dongerlel** [comment]
Ok i am reopening because after updating it still doesn't work for me.

**Comment by HOAIAN2** [comment]
To get hightest media quality, i use api that require auth, so you need to login.
