### ISSUE TITLE
Why does it work when videos or images open in model and not on home screen ?

### ISSUE THREAD

**Issue by funcbind** [HOAIAN2/Instagram-Downloader#11]
- I have to click on comments & open video/image in the model for the extension to work 
- Can it work directly from the home screen. Is it possible ? or some constraints because of which this is implemented like this ?

**Comment by HOAIAN2** [comment]
> * I have to click on comments & open video/image in the model for the extension to work
> * Can it work directly from the home screen. Is it possible ? or some constraints because of which this is implemented like this ?

![image](https://github.com/HOAIAN2/Instagram-Downloader/assets/98139595/95308aaa-5146-4c93-a6d4-4a6a2e897cc5)
So late, but now I have free time, and I'm implementing that.

**Comment by HOAIAN2** [comment]
Almost done, I'm testing your request right now. You can clone main branch to test it.
https://github.com/HOAIAN2/Instagram-Downloader/commit/e6d6834d6ccac9ed79ea08f2d1a27c12e149d16f

**Comment by HOAIAN2** [comment]
Done in release 5.1.0: https://github.com/HOAIAN2/Instagram-Downloader/releases/tag/v5.1.0
