### ISSUE TITLE
Private Account Post Problem

### ISSUE THREAD

**Issue by deadeye201** [HOAIAN2/Instagram-Downloader#13]
Hello, first of all, thank you very much for this awesome extension, it was working very well a few months ago, but now I can no longer download the posts shared by the followed hidden accounts, it cannot fetch any images, but there is no problem with stories, I think it has been like this for a few months, please can you fix this problem?

**Comment by HOAIAN2** [comment]
The problem happen because they deprecated hash api to get post id from post shortcode. I couldn't find the algorithm they use to parse private post to id, but I just found new api. I will try to fix that as soon as possible.

**Comment by HOAIAN2** [comment]
> Hello, first of all, thank you very much for this awesome extension, it was working very well a few months ago, but now I can no longer download the posts shared by the followed hidden accounts, it cannot fetch any images, but there is no problem with stories, I think it has been like this for a few months, please can you fix this problem?

I just push new version to Github (not release yet). Can you pull the main branch and test it ? I don't follow any private profile, I just private myself to test and it's work. Not you not reply in one week or everything work, I will release new version.
https://github.com/HOAIAN2/Instagram-Downloader/commit/2cc45344cbbe5bc5ed87d0f94fec3955273de28d

**Comment by deadeye201** [comment]
> > Hello, first of all, thank you very much for this awesome extension, it was working very well a few months ago, but now I can no longer download the posts shared by the followed hidden accounts, it cannot fetch any images, but there is no problem with stories, I think it has been like this for a few months, please can you fix this problem?
> 
> I just push new version to Github (not release yet). Can you pull the main branch and test it ? I don't follow any private profile, I just private myself to test and it's work. Not you not reply in one week or everything work, I will release new version. [2cc4534](https://github.com/HOAIAN2/Instagram-Downloader/commit/2cc45344cbbe5bc5ed87d0f94fec3955273de28d)

Sorry for late reply tested the new version and works fıne thanks a lot for the fix

**Comment by deadeye201** [comment]
@HOAIAN2 Hello again have a good day I realized today that the same problem is happening again can you check again please ?

**Comment by HOAIAN2** [comment]
> [@HOAIAN2](https://github.com/HOAIAN2) Hello again have a good day I realized today that the same problem is happening again can you check again please ?

Pull the latest branch again, I miss spell 1 variable name but I think it should fine. I not follow any private profile, I just private myself to test (it's worked). But you should test your own.

**Comment by deadeye201** [comment]
> > [@HOAIAN2](https://github.com/HOAIAN2) Hello again have a good day I realized today that the same problem is happening again can you check again please ?
> 
> Pull the latest branch again, I miss spell 1 variable name but I think it should fine. I not follow any private profile, I just private myself to test (it's worked). But you should test your own.

Tested works fine thanks a lot again
