### ISSUE TITLE
[Feature Request] File Naming, Username Sub Directories, Main Download Directory, 

### ISSUE THREAD

**Issue by syddharth** [HOAIAN2/Instagram-Downloader#3]
Firstly, kudos on the great extension.

I have a few feature suggestions, which I think would make the extension even more powerful: 
1. It'd be nice to have a naming convention, to the downloaded files. Something like : username_post-id_post-type_date-time etc. 
2. Download all files into respective username folders (along with the above naming convention)
3. Ability to choose default download directory.

**Comment by HOAIAN2** [comment]
Naming convention is great but choose Download folder only possible if user right click and 'save image as'.

**Comment by HOAIAN2** [comment]
Yeah, not sure if I can add new feature this week,. I decide to use /v1/ api for better photo quality and I currently busy now.

**Comment by HOAIAN2** [comment]
Done, I just add file naming convention and 2K resolution support for every photos and videos.
