### ISSUE TITLE
Please provide us Java or Php code as well thank

### ISSUE THREAD

**Issue by attaullahpro** [HOAIAN2/Instagram-Downloader#5]

**Comment by HOAIAN2** [comment]
Extension only work with Javascript, but you can use api that I use on my code to implement on any language.

**Comment by HOAIAN2** [comment]
But you have to carefully because if you get data from (not from browser) like a nodejs or php server, Instagram can block your account ( they can validate buy csrf, user agent,....)

**Comment by attaullahpro** [comment]
Thanks! 
My logic in my java app is that I use the html source code of from link and then get the video_url to download a video, or if a video is private, then the app asks the user to login, but you very well know that's why I request conversion.
i did not find what API you are using in JS.

**Comment by attaullahpro** [comment]
Thanks! 
My logic in my java app is that I use the html source code of from link and then get the video_url to download a video, or if a video is private, then the app asks the user to login, but you very well know that's why I request conversion.
i did not find what API you are using in JS.

**Comment by HOAIAN2** [comment]
> Thanks!  My logic in my java app is that I use the html source code of from link and then get the video_url to download a video, or if a video is private, then the app asks the user to login, but you very well know that's why I request conversion. i did not find what API you are using in JS.

You can found on `src/js/post.js` and `src/js/story.js` every function that I call `fetch` api from browser.

**Comment by attaullahpro** [comment]
Dear can you say about
const PROFILE_HASH = '69cba40317214236af40e7efa697781d'
const POST_HASH = '9f8827793ef34641b2fb195d4d41151c'

what are these hashes please

**Comment by HOAIAN2** [comment]
> Dear can you say about const PROFILE_HASH = '69cba40317214236af40e7efa697781d' const POST_HASH = '9f8827793ef34641b2fb195d4d41151c'
> 
> what are these hashes please

That are special hashes Instagram use to call API, I found that in network tab.

**Comment by attaullahpro** [comment]
Thanks for the response,
Can we use these hashes (I mean these hashes for public ) or we need own hashes etc,

**Comment by HOAIAN2** [comment]
> Thanks for the response, Can we use these hashes (I mean these hashes for public ) or we need own hashes etc,

If you change hashes, api will 404 respone, so you cannot change that.

**Comment by HOAIAN2** [comment]
It's took me 1 week to found that ( 6 month ago).
