### ISSUE TITLE
Feature Request & Extension Suggestion

### ISSUE THREAD

**Issue by MoonLightStorm** [HOAIAN2/Instagram-Downloader#6]
Hi, thank you for this great extension.

If possible, add the ability to right-click on each post to open a new tab with the same name as the original file

Also, if possible, add a feature to download thumbnail previews of videos with the highest quality

I like to open each photo or video in a new tab and save it with the original name.

Best regards

**Comment by HOAIAN2** [comment]
Hmmm, you can drag and drop photos/videos to new tab. It's gonna open default link respone from api and you can save with original name.

**Comment by MoonLightStorm** [comment]
Hello, thank you for your reply

I knew that, but if there was an easier way, by putting a shortcut to quickly open in a new tab to save time

Also, is there any hope of putting the download preview thumbnails?

Best regards

**Comment by HOAIAN2** [comment]
If I do that, I must be use another options to select images, because I use right click to select.

**Comment by HOAIAN2** [comment]
@MoonLightStorm  Hey there, I just add new select multi image on Extension (click on ```Photos```  to toggle it) then you can left click to select just like how you select image on Facebook mobile. I will test some options and release version latter.

**Comment by HOAIAN2** [comment]
You can clone branch ```main``` and use that.

**Comment by HOAIAN2** [comment]
IDK, I have no issuse.
