### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by dongerlel** [HOAIAN2/Instagram-Downloader#7]
Hi, amazing extension it's working perfectly. I just wanted to ask, can you add a simple button to only download the video playing? Like have something small on the video itself without the need to open any additional windows.

![image](https://github.com/HOAIAN2/Instagram-Downloader/assets/12804761/c4f65503-fcf8-4a72-a37e-5115014a509e)

thank you

**Comment by HOAIAN2** [comment]
If only a button, yes. But they don't put URL on video, they but a blob on theme so you still need to fetch all data. That why I make a window to download.

**Comment by dongerlel** [comment]
i would also like to report a bug

if you are in a conversation with some one, https://www.instagram.com/direct/t/10017blabla19743/
then it doesn't detect that you are wring and it activates the keyboard shortcuts

**Comment by HOAIAN2** [comment]
> 

Please drag and drop video or img direct in github comment.

**Comment by HOAIAN2** [comment]
> i would also like to report a bug
> 
> if you are in a conversation with some one, https://www.instagram.com/direct/t/10017blabla19743/ then it doesn't detect that you are wring and it activates the keyboard shortcuts

Maybe it was fix, I just change ignore event keydown to event target, checkout main branch.

**Comment by dongerlel** [comment]
> > i would also like to report a bug
> > if you are in a conversation with some one, https://www.instagram.com/direct/t/10017blabla19743/ then it doesn't detect that you are wring and it activates the keyboard shortcuts
> 
> Maybe it was fix, I just change ignore event keydown to event target, checkout main branch.

It doesn't work unfortunately. When i press D when writing to a friend it opens up the asian chick

**Comment by dongerlel** [comment]
> > 
> 
> Please drag and drop video or img direct in github comment.

i don't know what you mean

**Comment by HOAIAN2** [comment]
It only open when you chat or something? I have no issue on any other page.

**Comment by HOAIAN2** [comment]
> > > i would also like to report a bug
> > > if you are in a conversation with some one, https://www.instagram.com/direct/t/10017blabla19743/ then it doesn't detect that you are wring and it activates the keyboard shortcuts
> > 
> > 
> > Maybe it was fix, I just change ignore event keydown to event target, checkout main branch.
> 
> It doesn't work unfortunately. When i press D when writing to a friend it opens up the asian chick

OK, I see, they don't use input or textarea. I gonna fix that as soon as possible.

**Comment by dongerlel** [comment]
> > > > i would also like to report a bug
> > > > if you are in a conversation with some one, https://www.instagram.com/direct/t/10017blabla19743/ then it doesn't detect that you are wring and it activates the keyboard shortcuts
> > > 
> > > 
> > > Maybe it was fix, I just change ignore event keydown to event target, checkout main branch.
> > 
> > 
> > It doesn't work unfortunately. When i press D when writing to a friend it opens up the asian chick
> 
> OK, I see, they don't use input or textarea. I gonna fix that as soon as possible.

it's fixed now thank you
