### ISSUE TITLE
Extension covers functions in DMs

### ISSUE THREAD

**Issue by dongerlel** [HOAIAN2/Instagram-Downloader#8]
![image](https://github.com/HOAIAN2/Instagram-Downloader/assets/12804761/7c4bc485-9943-4ecd-a003-e0d62600bc3d)

**Comment by HOAIAN2** [comment]
Ok, may be I gonna hide that on instagram direct

**Comment by HOAIAN2** [comment]
You can try custom css before I fix it.

**Comment by HOAIAN2** [comment]
> ![image](https://user-images.githubusercontent.com/12804761/260330749-7c4bc485-9943-4ecd-a003-e0d62600bc3d.png)

Do you need download video or image on Instagram Direct ?

**Comment by dongerlel** [comment]
> 

no not really i don't think it's needed inside direct

**Comment by HOAIAN2** [comment]
> > 
> 
> no not really i don't think it's needed inside direct

It work on main branch but I'm not sure it can work on Firefox.
