### ISSUE TITLE
Add new feature

### ISSUE THREAD

**Issue by sardar-mahdi** [HOAIAN2/Instagram-Downloader#9]
Hello, thank you for your excellent project, it was very useful for me
It is possible to add a feature to download all highlights with one click
It would be great if you could add this
Thank you

**Comment by HOAIAN2** [comment]
?? What do you mean, you call select all images

**Comment by sardar-mahdi** [comment]
Yes, exactly
Create a button that will pop when we click on the download option
There should be a select all button that selects all items when we click on it
Select all the stories and posts so that we can download them more easily

**Comment by HOAIAN2** [comment]
Im' not sure about story, but i can download all post from user.

**Comment by sardar-mahdi** [comment]
With one click, it is possible to select all posts and download them
Or should we choose them one by one?

**Comment by HOAIAN2** [comment]
Not sure but it very heavy, almost crash your browser
